# Build Stage Start
FROM node:14-alpine as builder
WORKDIR /markdown-editor
COPY package*.json ./
RUN npm install
COPY . .
RUN yarn build

# Run Stage Start
FROM nginx:1.21-alpine
# COPY ./default-prod.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /markdown-editor/build /usr/share/nginx/html