version: '3'
services:
  markdown-editor:
    ports:
      - "8080:80"
    build:
      context: .
      dockerfile: Dockerfile.prod
# command: npm start
# stdin_open: true
# tty: true

# "build .": Indica donde está el Dockerfile a utilizar para crear el contenedor. Al definir “.” considerará el Dockerfile existente en directorio actual.